# Generated by Django 4.0.4 on 2022-10-25 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=50, null=True)),
                ('branch_code', models.CharField(max_length=200, null=True, unique=True)),
                ('branch_name', models.CharField(max_length=200, unique=True)),
                ('is_branch', models.BooleanField(default=True, null=True)),
                ('branch_mnemonic', models.CharField(max_length=7, null=True)),
                ('sbs_code', models.CharField(max_length=50, null=True)),
                ('branch_address', models.CharField(max_length=450, null=True)),
                ('created_by', models.CharField(max_length=450, null=True)),
                ('creat_date', models.CharField(max_length=450, null=True)),
                ('status', models.CharField(max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('displayname', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(default='N/A', max_length=200, null=True)),
                ('employeeID', models.CharField(max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_no', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.FloatField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('qtr', models.CharField(max_length=30)),
                ('payermobile_no', models.CharField(max_length=30)),
                ('tstatus', models.CharField(default='Payment SuccessFull', editable=False, max_length=300)),
                ('address1', models.CharField(max_length=1000)),
                ('address2', models.CharField(max_length=1000)),
                ('address3', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('txnId', models.CharField(editable=False, max_length=30, null=True)),
                ('rowNo', models.CharField(editable=False, max_length=30, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('status', models.BooleanField(default=False)),
                ('txn_date', models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 14, 34, 65102), editable=False, null=True)),
                ('input_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dncctaxpay.user')),
            ],
        ),
    ]
