# Generated by Django 4.0.4 on 2022-10-25 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dncctaxpay', '0002_alter_branch_branch_code_alter_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dncctaxpay.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='branchname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dncctaxpay.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 38, 57, 346566), editable=False, null=True),
        ),
    ]
